### ISSUE TITLE
App fails to sign in

### ISSUE THREAD

**Issue by extremevertigo** [artberri/cordova-plugin-play-games-services#13]
I needed to use 
"cordova plugin add cordova-plugin-play-games-services --variable APP_ID=<...> --variable ANDROID_PLAY_SERVICES_GAMES_VERSION=18.0.1"

In the device ready event I call.
" cordova.plugins.playGamesServices.auth(function() {
        // On logged in
    }, function() {
        // On not logged in
    });
"
When I open the app I get the google play icon at the top saying it is connecting to the google play service.  Then a couple of seconds later I get a pop up window that I failed to sign in.  I am not sure where to proceed from here on resolving this issue.  Any tips or advise would be much appreciated.  
Is this plugin still a reliable plugin to use?  
I just want to be able to use google play leaderboards and achievements in my Cordova project.  Thank you in advance :)

**Comment by extremevertigo** [comment]
This is the log from android studio in regards to it not working:
"W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: ll@13a1b37
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1562)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
        at ce.b(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):1)
        at ce.a(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):5)
        at lm.A(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):10)
        at kx.a(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):3)
        at dx.run(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iv.run(:com.google.android.gms.dynamite_measurementdynamite@201817068@20.18.17 (100700-0):15)"

**Comment by TheBosZ** [comment]
For me, I had to sign the debug APK using the keystore I linked in the Play Console.

After that, I was able to get `SIGN_IN_SUCCESS`

**Comment by lithiumhax** [comment]
I'm having the same problem, I get the "Connecting to Play Games" banner animation at the top, but then I get the Error message: "Failed to sign in.  Please check your network connections and try again".

Can anyone help?
Thanks!
